grpc:
  client:
    payment-service:
      address: 'static://payment-service:9091'
      negotiationType: plaintext
    proxy-service:
      address: 'static://proxy-service:9092'
      negotiationType: plaintext